export const catalogData = [
  {
    "IME PROIZVODA - do 60 znakova":
      "Kolutići i krakovi lignje Patagonica 425 g Perla",
    "PRODUCT NAME - up to 60 characters":
      "Patagonica squid rings and arms 425 g Perla",
    "IME PROIZVODA - skraceno": "Kolutići i krakovi lignje Patagonica Perla",
    "PRODUCT NAME - short": "Patagonica squid rings and arms Perla",
    "LATINSKI NAZIV - do 60 znakova": "Loligo Patagonica",
    "Kataloški broj: ": 21046,
    FeaturedPerla: "DA",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "8 x 425 g, Perla, 0% leda",
    "OPIS ENGLESKI": "8 x 425 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "425 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 108,
    "NAČIN SMRZAVANJA": "IQF",
    "METHOD OF FREEZING": "IQF",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "NE",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Lignja Patagonica 525 g Perla",
    "PRODUCT NAME - up to 60 characters": "Patagonica squid 525 g Perla",
    "IME PROIZVODA - skraceno": "Lignja Patagonica Perla",
    "PRODUCT NAME - short": "Patagonica squid Perla",
    "LATINSKI NAZIV - do 60 znakova": "Loligo Patagonica ",
    "Kataloški broj: ": 21047,
    FeaturedPerla: "DA",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "6 x 525 g, Perla, 0% leda",
    "OPIS ENGLESKI": "6 x 525 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "525 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 108,
    "NAČIN SMRZAVANJA": "IQF",
    "METHOD OF FREEZING": "IQF",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "NE",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Lignja očišćena Patagonica 450 g Perla",
    "PRODUCT NAME - up to 60 characters":
      "Squid cleaned Patagonica 450 g Perla",
    "IME PROIZVODA - skraceno": "Lignja očišćena Patagonica Perla",
    "PRODUCT NAME - short": "Squid cleaned Patagonica Perla",
    "LATINSKI NAZIV - do 60 znakova": "Loligo Patagonica ",
    "Kataloški broj: ": 21048,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "10 x 450 g, Perla, 0% leda",
    "OPIS ENGLESKI": "10 x 450 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "450 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 81,
    "NAČIN SMRZAVANJA": "IQF",
    "METHOD OF FREEZING": "IQF",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "NE",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Tuna steak 250 g Perla",
    "PRODUCT NAME - up to 60 characters": "Tuna steak 250 g Perla",
    "IME PROIZVODA - skraceno": "Tuna steak Perla",
    "PRODUCT NAME - short": "Tuna steak Perla",
    "LATINSKI NAZIV - do 60 znakova": "Thunnus obesus",
    "Kataloški broj: ": 20964,
    FeaturedPerla: "DA",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "10 x 250 g, Perla, 0% leda",
    "OPIS ENGLESKI": "10 x 250 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "250 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 81,
    "NAČIN SMRZAVANJA": "IQF",
    "METHOD OF FREEZING": "IQF",
    "Certifikat 'MSC' (DA/NE)": "DA",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "DA",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Bodečnjak očišćeni Perla",
    "PRODUCT NAME - up to 60 characters": "Perla cleaned barb",
    "IME PROIZVODA - skraceno": "Bodečnjak očišćeni Perla",
    "PRODUCT NAME - short": "Perla cleaned barb",
    "LATINSKI NAZIV - do 60 znakova": "Sebastes marinus",
    "Kataloški broj: ": 20831,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "6 kg",
    "OPIS ENGLESKI": "6 kg, Frozen",
    "Jedinica mjere": "kg",
    "Težina po jedinici mjere": "6 kg",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 63,
    "NAČIN SMRZAVANJA": "IQF",
    "METHOD OF FREEZING": "IQF",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "NE",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Sipa kockice 235 g Perla",
    "PRODUCT NAME - up to 60 characters": "Cuttlefish cubes 235 g Perla",
    "IME PROIZVODA - skraceno": "Sipa kockice Perla",
    "PRODUCT NAME - short": "Cuttlefish cubes Perla",
    "LATINSKI NAZIV - do 60 znakova": "Sepia officinalis/pharaonis",
    "Kataloški broj: ": 20835,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "16 x 235 g, Perla, 0% leda",
    "OPIS ENGLESKI": "16 x 235 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "235 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 36,
    "NAČIN SMRZAVANJA": "IQF",
    "METHOD OF FREEZING": "IQF",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "DA",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Škampi za buzaru 375 g Perla",
    "PRODUCT NAME - up to 60 characters": "Shrimp for buzara 375",
    "IME PROIZVODA - skraceno": "Škampi za buzaru Perla",
    "PRODUCT NAME - short": "Shrimp for buzara",
    "LATINSKI NAZIV - do 60 znakova": "Nephrops Norvegicus",
    "Kataloški broj: ": 20856,
    FeaturedPerla: "DA",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "6 x 375 g, Perla, 0% leda",
    "OPIS ENGLESKI": "6 x 375 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "375 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 110,
    "NAČIN SMRZAVANJA": "IQF",
    "METHOD OF FREEZING": "IQF",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "NE",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Oslić fileti 500 g Perla",
    "PRODUCT NAME - up to 60 characters": "Hake fillets 500 g Perla",
    "IME PROIZVODA - skraceno": "Oslić fileti Perla",
    "PRODUCT NAME - short": "Hake fillets Perla",
    "LATINSKI NAZIV - do 60 znakova": "Merluccius hubbsi",
    "Kataloški broj: ": 21049,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "10 x 500 g, Perla, 0% leda",
    "OPIS ENGLESKI": "10 x 500 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "500 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 81,
    "NAČIN SMRZAVANJA": "IQF",
    "METHOD OF FREEZING": "IQF",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "DA",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Lignja Peškafondo 500 g Perla",
    "PRODUCT NAME - up to 60 characters": "Squid Peškafondo 500 g Perla",
    "IME PROIZVODA - skraceno": "Lignja Peškafondo Perla",
    "PRODUCT NAME - short": "Squid Peškafondo Perla",
    "LATINSKI NAZIV - do 60 znakova": "Loligo Reynaudi",
    "Kataloški broj: ": 20968,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "8 x 500 g, Perla, 0% leda",
    "OPIS ENGLESKI": "8 x 500 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "500 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 88,
    "NAČIN SMRZAVANJA": "-",
    "METHOD OF FREEZING": "-",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "DA",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Vongole 750 g Perla",
    "PRODUCT NAME - up to 60 characters": "Vongole 750 g Perla",
    "IME PROIZVODA - skraceno": "Vongole Perla",
    "PRODUCT NAME - short": "Vongole Perla",
    "LATINSKI NAZIV - do 60 znakova": "Meretrix Lyrata",
    "Kataloški broj: ": 20841,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "9 x 750 g, Perla, 0% leda",
    "OPIS ENGLESKI": "9 x 750 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "750 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 108,
    "NAČIN SMRZAVANJA": "IQF",
    "METHOD OF FREEZING": "IQF",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "DA",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Temeljac od škampa 450 g Perla",
    "PRODUCT NAME - up to 60 characters": "Shrimp stock 450 g Perla",
    "IME PROIZVODA - skraceno": "Temeljac od škampa Perla",
    "PRODUCT NAME - short": "Shrimp stock Perla",
    "LATINSKI NAZIV - do 60 znakova": "-",
    "Kataloški broj: ": 20985,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "16 x 450 g, Perla, 0% leda",
    "OPIS ENGLESKI": "16 x 450 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "450 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 20,
    "NAČIN SMRZAVANJA": "-",
    "METHOD OF FREEZING": "-",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "NE",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Temeljac riblji 450 g Perla",
    "PRODUCT NAME - up to 60 characters": "Fish stock 450 g Perla",
    "IME PROIZVODA - skraceno": "Temeljac riblji Perla",
    "PRODUCT NAME - short": "Fish stock Perla",
    "LATINSKI NAZIV - do 60 znakova": "-",
    "Kataloški broj: ": 20986,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "16 x 450 g, Perla, 0% leda",
    "OPIS ENGLESKI": "16 x 450 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "450 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 20,
    "NAČIN SMRZAVANJA": "-",
    "METHOD OF FREEZING": "-",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "NE",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Krakovi za peku i salatu 1000 g Perla",
    "PRODUCT NAME - up to 60 characters":
      "Crab sticks for baking and salad 1000 g Perla",
    "IME PROIZVODA - skraceno": "Krakovi za peku i salatu Perla",
    "PRODUCT NAME - short": "Crab sticks for baking and salad Perla",
    "LATINSKI NAZIV - do 60 znakova": "Dosidicus gigas",
    "Kataloški broj: ": 21021,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "8 x 1 kg, Perla, 0% leda",
    "OPIS ENGLESKI": "8 x 1 kg, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "1 kg",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 80,
    "NAČIN SMRZAVANJA": "-",
    "METHOD OF FREEZING": "-",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "NE",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Bakalar Lofoten namočen očišćen Perla",
    "PRODUCT NAME - up to 60 characters": "Cod Lofoten soaked cleaned Perla",
    "IME PROIZVODA - skraceno": "Bakalar Lofoten namočen očišćen Perla",
    "PRODUCT NAME - short": "Cod Lofoten soaked cleaned Perla",
    "LATINSKI NAZIV - do 60 znakova": "Gadus morhua",
    "Kataloški broj: ": 20861,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "8 kg, Perla, 0% leda",
    "OPIS ENGLESKI": "8 kg, Frozen",
    "Jedinica mjere": "kg",
    "Težina po jedinici mjere": "8 kg",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 40,
    "NAČIN SMRZAVANJA": "IQF",
    "METHOD OF FREEZING": "IQF",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "DA",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "DA",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
    "SPECIFIKACIJE: Ukoliko se uz proizvod uploada i pdf specifikacija, taj dokument treba imati ime po kataloškom broju i ekstenziju pdf":
      "",
  },
  {
    "IME PROIZVODA - do 60 znakova": "Sipa crnilo 2x4 g",
    "PRODUCT NAME - up to 60 characters": "Sipa black 2x4 g",
    "IME PROIZVODA - skraceno": "Sipa crnilo",
    "PRODUCT NAME - short": "Cuttlefish black ink",
    "LATINSKI NAZIV - do 60 znakova": "-",
    "Kataloški broj: ": 14026,
    FeaturedPerla: "",
    "Kategorija kojoj proizvod pripada:": "PERLA",
    "Kategorija kojoj proizvod pripada ENG:": "PERLA",
    "Perla HORECA (DA/NE)": "NE",
    "OPIS (DO 300 ZNAKOVA)": "100 x 8 g, Perla, 0% leda",
    "OPIS ENGLESKI": "100 x 8 g, Frozen",
    "Jedinica mjere": "kom",
    "Težina po jedinici mjere": "8 g",
    "Ostale jedinice: Veličina/pecatura/broj kom u kg: ": "-",
    "Other units: Size/patch/number of pcs in kg:": "-",
    "Vrijednost ukoliko je prethodno polje ispunjeno ": "-",
    "Zona ulova: ": "",
    "Broj kutija na paleti:": 280,
    "NAČIN SMRZAVANJA": "-",
    "METHOD OF FREEZING": "-",
    "Certifikat 'MSC' (DA/NE)": "NE",
    "IFS Food": "NE",
    "Certifikat 'Živjeti Zdravo' (DA/NE)": "NE",
    "Polje ostavljeno za neki buduci certifikat (ne ispunjavati)": "NE",
    'OZNAKA "Novo" (DA/NE)': "NE",
    'OZNAKA: "Novo pakiranje" (DA/NE)': "NE",
  },
];
