// povuci preko getAllPerlaProizvodi u get static props na nekom pageu i sa json.stringify pretvori u ovakav json i tu kopiraj
// to treba napraviti kad dodaju neki novi perla proizvod. Sad ih je tu 20ak

export const perlaProizvodiLocal = [
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: null,
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Salata od hobotnice 210 g",
        imeProizvodaDo60ZnakovaEng: "Octopus salad 210 g",
        jedinicaMjere: "kom",
        kataloskiBroj: "111111",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "-",
        marketinskoImePerlaProizvodaEng: "Octopus salad 210 g",
        marketinskoImePerlaProizvodaHr: "Salata od hobotnice 210 g",
        nacinSmrzavanja: "-",
        opisEngDo300Znakova:
          "Marinated octopus salad with green olives and onions in sunflower oil.",
        opisHrDo300Znakova:
          "Salata od marinirane hobotice sa zelenim maslinama i lukovicama u suncokretovu ulju.",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "-",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: null,
        tezinaPoJediniciMjere: "210 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2025/11/SALATA-OD-HOBOTNICE-04-_transparent.png",
        },
      },
      title: "Salata od hobotnice 210 g",
      proizvodId: 2078,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "60",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Hobotnica marinirana 210 g",
        imeProizvodaDo60ZnakovaEng: "Marinated octopus 210 g",
        jedinicaMjere: "kom",
        kataloskiBroj: "13082",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Octopus vulgaris/cyaneus",
        marketinskoImePerlaProizvodaEng: "Marinated octopus 210 g",
        marketinskoImePerlaProizvodaHr: "Hobotnica marinirana 210 g",
        nacinSmrzavanja: "-",
        opisEngDo300Znakova: "xx",
        opisHrDo300Znakova: "xx",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "-",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "20 x 210 g",
        tezinaPoJediniciMjere: "20 x 210 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/13082.webp",
        },
      },
      title: "Hobotnica marinirana 210 g",
      proizvodId: 1445,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "60",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Kozica marinirana 210 g",
        imeProizvodaDo60ZnakovaEng: "Marinated shrimp 210 g",
        jedinicaMjere: "kom",
        kataloskiBroj: "13083",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Penaeus Vannamei",
        marketinskoImePerlaProizvodaEng: "Marinated shrimp 210 g",
        marketinskoImePerlaProizvodaHr: "Kozica marinirana 210 g",
        nacinSmrzavanja: "-",
        opisEngDo300Znakova: "xx",
        opisHrDo300Znakova: "xx",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "20 x 210 g",
        tezinaPoJediniciMjere: "20 x 210 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/13083.webp",
        },
      },
      title: "Kozica marinirana 210 g",
      proizvodId: 1444,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "40",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Hobotnica očišćena 1000g",
        imeProizvodaDo60ZnakovaEng: "Octopus ball type cleaned 1000 g",
        jedinicaMjere: "kom",
        kataloskiBroj: "21062",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Octopus Vulgaris",
        marketinskoImePerlaProizvodaEng: "Octopus ball type cleaned 1000 g",
        marketinskoImePerlaProizvodaHr: "Hobotnica očišćena 1000g",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "xzz",
        opisHrDo300Znakova: "ccx",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "-",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "-",
        tezinaPoJediniciMjere: "10 x 1000 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/21062.webp",
        },
      },
      title: "Hobotnica očišćena 1000g",
      proizvodId: 1443,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "150",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Meso jadranskih kozica 200 g Perla",
        imeProizvodaDo60ZnakovaEng: "Adriatic shrimp tails PUD 500 g. ",
        jedinicaMjere: "kom",
        kataloskiBroj: "21052",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Parapenaeus longirostris",
        marketinskoImePerlaProizvodaEng: "Adriatic shrimp tails PUD 500 g. ",
        marketinskoImePerlaProizvodaHr: "Meso jadranskih kozica 200 g Perla",
        nacinSmrzavanja: "-",
        opisEngDo300Znakova: "a",
        opisHrDo300Znakova: "a",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "-",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "-",
        tezinaPoJediniciMjere: "25 x 200 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/21052.webp",
        },
      },
      title: "Meso jadranskih kozica 200 g Perla",
      proizvodId: 1442,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "81",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Oslić očišćeni 450 g",
        imeProizvodaDo60ZnakovaEng: "Hake HGT 450 g. ",
        jedinicaMjere: "kom",
        kataloskiBroj: "21030",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Merluccius hubbsi",
        marketinskoImePerlaProizvodaEng: "Hake HGT 450 g. ",
        marketinskoImePerlaProizvodaHr: "Oslić očišćeni 450 g",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "xx",
        opisHrDo300Znakova: "xx",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "8 x 450 g",
        tezinaPoJediniciMjere: "450 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/21030.webp",
        },
      },
      title: "Oslić očišćeni 450 g",
      proizvodId: 1441,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "81",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Kolutići i krakovi lignje 350 g",
        imeProizvodaDo60ZnakovaEng: "Squid rings and tentacles 350 g",
        jedinicaMjere: "kom",
        kataloskiBroj: "20934",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Loligo duvaucelli",
        marketinskoImePerlaProizvodaEng: "Squid rings and tentacles",
        marketinskoImePerlaProizvodaHr: "Kolutići i krakovi lignje",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "ccc",
        opisHrDo300Znakova: "ccc",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "14 x 350g",
        tezinaPoJediniciMjere: "350 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20934.webp",
        },
      },
      title: "Kolutići i krakovi lignje 350 g",
      proizvodId: 1439,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "280",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Sipa crnilo 8 g (2 x 4 g)",
        imeProizvodaDo60ZnakovaEng: "Cuttlefish ink 8 g (2 x 4 g)",
        jedinicaMjere: "kom",
        kataloskiBroj: "14026",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: null,
        marketinskoImePerlaProizvodaEng: "Cuttlefish ink",
        marketinskoImePerlaProizvodaHr: "Sipa crnilo",
        nacinSmrzavanja: "-",
        opisEngDo300Znakova: "xx",
        opisHrDo300Znakova: "xx",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Veličina",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "100 x 8 g",
        tezinaPoJediniciMjere: "2 x 4 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/14026.webp",
        },
      },
      title: "Sipa crnilo 2×4 g",
      proizvodId: 1438,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "40",
        certifikatMsc: null,
        certifikatZivjetiZdravo: true,
        featuredPerlaProduct: true,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Bakalar Lofoten namočen očišćen Perla",
        imeProizvodaDo60ZnakovaEng: "Stockfish fillets - soaked",
        jedinicaMjere: "kg",
        kataloskiBroj: "20861",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Gadus morhua",
        marketinskoImePerlaProizvodaEng: "Cod Lofoten soaked & cleaned Perla",
        marketinskoImePerlaProizvodaHr: "Bakalar Lofoten namočen očišćen Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "a",
        opisHrDo300Znakova: "a",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "8 kg",
        tezinaPoJediniciMjere: "8 kg",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20861.webp",
        },
      },
      title: "Bakalar Lofoten namočen očišćen Perla",
      proizvodId: 1437,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "64",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Gavun 1000 g",
        imeProizvodaDo60ZnakovaEng: "Smelt 1000 g",
        jedinicaMjere: "kom",
        kataloskiBroj: "20281",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Atherina Boyeri ",
        marketinskoImePerlaProizvodaEng: "Smelt 1000 g",
        marketinskoImePerlaProizvodaHr: "Gavun 1000 g",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "ccc",
        opisHrDo300Znakova: "ccc",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "10 x 1000 g",
        tezinaPoJediniciMjere: "1000 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20281.webp",
        },
      },
      title: "Gavun 1000 g",
      proizvodId: 1436,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "80",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Krakovi za peku i salatu 1000 g",
        imeProizvodaDo60ZnakovaEng: "Giant squid tentacles 1000 g. tray",
        jedinicaMjere: "kom",
        kataloskiBroj: "21021",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Dosidicus gigas",
        marketinskoImePerlaProizvodaEng: "Giant squid tentacles 1000 g. tray",
        marketinskoImePerlaProizvodaHr: "Krakovi za peku i salatu Perla",
        nacinSmrzavanja: "-",
        opisEngDo300Znakova: "x",
        opisHrDo300Znakova: "x",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "8 x 1 kg",
        tezinaPoJediniciMjere: "1 kg",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2025/11/Krakovi_za_peku_i_salatu_Perla_pack_transparent.png",
        },
      },
      title: "Krakovi za peku i salatu 1000 g Perla",
      proizvodId: 1435,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "20",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: true,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Temeljac riblji 450 g Perla",
        imeProizvodaDo60ZnakovaEng: "Fish stock 450 g Perla",
        jedinicaMjere: "kom",
        kataloskiBroj: "20986",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "-",
        marketinskoImePerlaProizvodaEng: "Fish stock Perla",
        marketinskoImePerlaProizvodaHr: "Temeljac riblji Perla",
        nacinSmrzavanja: "-",
        opisEngDo300Znakova: "x",
        opisHrDo300Znakova: "x",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "16 x 450g",
        tezinaPoJediniciMjere: "450 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20986.webp",
        },
      },
      title: "Temeljac riblji 450 g Perla",
      proizvodId: 1434,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "20",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Temeljac od škampa 450 g Perla",
        imeProizvodaDo60ZnakovaEng: "Scampi stock 450 g Perla",
        jedinicaMjere: "kom",
        kataloskiBroj: "20985",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "-",
        marketinskoImePerlaProizvodaEng: "Scampi stock Perla",
        marketinskoImePerlaProizvodaHr: "Temeljac od škampa Perla",
        nacinSmrzavanja: "-",
        opisEngDo300Znakova: "a",
        opisHrDo300Znakova: "a",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "16 x 450g",
        tezinaPoJediniciMjere: "450 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20985.webp",
        },
      },
      title: "Temeljac od škampa 450 g Perla",
      proizvodId: 1433,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "108",
        certifikatMsc: null,
        certifikatZivjetiZdravo: true,
        featuredPerlaProduct: true,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Vongole 750 g Perla",
        imeProizvodaDo60ZnakovaEng: "White whole clams 750 g Perla",
        jedinicaMjere: "kom",
        kataloskiBroj: "20841",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Meretrix lyrata",
        marketinskoImePerlaProizvodaEng: "White whole clams",
        marketinskoImePerlaProizvodaHr: "Vongole Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "s",
        opisHrDo300Znakova: "s",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "9 x 750 g",
        tezinaPoJediniciMjere: "750 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20841.webp",
        },
      },
      title: "Vongole 750 g Perla",
      proizvodId: 1432,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "88",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Lignja Peškafondo 500 g Perla",
        imeProizvodaDo60ZnakovaEng: "Atlantic squid WR 500 g.",
        jedinicaMjere: "kom",
        kataloskiBroj: "20968",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Loligo pealeii",
        marketinskoImePerlaProizvodaEng: "Atlantic squid WR 500 g.",
        marketinskoImePerlaProizvodaHr: "Lignja Peškafondo Perla",
        nacinSmrzavanja: "-",
        opisEngDo300Znakova: "s",
        opisHrDo300Znakova: "s",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "8 x 500 g",
        tezinaPoJediniciMjere: "500 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20968.webp",
        },
      },
      title: "Lignja Peškafondo 500 g Perla",
      proizvodId: 1431,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "81",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Oslić fileti 500 g Perla",
        imeProizvodaDo60ZnakovaEng: "Hake fillets 500 g Perla",
        jedinicaMjere: "kom",
        kataloskiBroj: "21049",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Merluccius hubbsi",
        marketinskoImePerlaProizvodaEng: "Hake fillets Perla",
        marketinskoImePerlaProizvodaHr: "Oslić fileti Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "s",
        opisHrDo300Znakova: "s",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "-",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "-",
        tezinaPoJediniciMjere: "500 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/21049.webp",
        },
      },
      title: "Oslić fileti 500 g Perla",
      proizvodId: 1430,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "110",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: true,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Škampi za buzaru 375 g Perla",
        imeProizvodaDo60ZnakovaEng: "Scampi WR 375 g. ",
        jedinicaMjere: "kom",
        kataloskiBroj: "20856",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Nephrops Norvegicus",
        marketinskoImePerlaProizvodaEng: "Scampi alla buzara",
        marketinskoImePerlaProizvodaHr: "Škampi za buzaru Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "x",
        opisHrDo300Znakova: "x",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "6 x 375 g",
        tezinaPoJediniciMjere: "375 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20856.webp",
        },
      },
      title: "Škampi za buzaru 375 g Perla",
      proizvodId: 1429,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "36",
        certifikatMsc: null,
        certifikatZivjetiZdravo: true,
        featuredPerlaProduct: true,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Sipa kockice 235 g Perla",
        imeProizvodaDo60ZnakovaEng: "Cuttlefish cubes 235 g Perla",
        jedinicaMjere: "kom",
        kataloskiBroj: "20835",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Sepia officinalis",
        marketinskoImePerlaProizvodaEng: "Cuttlefish cubes Perla",
        marketinskoImePerlaProizvodaHr: "Sipa kockice Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "x",
        opisHrDo300Znakova: "x",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "-",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "-",
        tezinaPoJediniciMjere: "235 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20835.webp",
        },
      },
      title: "Sipa kockice 235 g Perla",
      proizvodId: 1428,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "81",
        certifikatMsc: true,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Tuna steak 250 g Perla MSC",
        imeProizvodaDo60ZnakovaEng: "Tuna steak 250 g Perla MSC",
        jedinicaMjere: "kom",
        kataloskiBroj: "20964",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Thunnus albacares",
        marketinskoImePerlaProizvodaEng: "Tuna steak Perla MSC",
        marketinskoImePerlaProizvodaHr: "Tuna steak Perla MSC",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "x",
        opisHrDo300Znakova: "x",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "10 x 250 g",
        tezinaPoJediniciMjere: "250 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20964.webp",
        },
      },
      title: "Tuna steak 250 g Perla MSC",
      proizvodId: 1427,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "81",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Lignja očišćena Patagonica 450 g Perla",
        imeProizvodaDo60ZnakovaEng:
          "Patagonian squid tubes and tentacles cleaned 450 g.",
        jedinicaMjere: "kom",
        kataloskiBroj: "21048",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Loligo gahi",
        marketinskoImePerlaProizvodaEng:
          "Patagonian squid tubes and tentacles cleaned 450 g.",
        marketinskoImePerlaProizvodaHr: "Lignja očišćena Patagonica Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "za",
        opisHrDo300Znakova: "z",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "10 x 450 g",
        tezinaPoJediniciMjere: "450 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/21048.webp",
        },
      },
      title: "Lignja očišćena Patagonica 450 g Perla",
      proizvodId: 1426,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "108",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Lignja Patagonica 525 g Perla",
        imeProizvodaDo60ZnakovaEng: "Patagonian squid WR 525 g.",
        jedinicaMjere: "kom",
        kataloskiBroj: "21047",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Loligo gahi",
        marketinskoImePerlaProizvodaEng: "Patagonian squid WR 525 g.",
        marketinskoImePerlaProizvodaHr: "Lignja Patagonica Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "cc",
        opisHrDo300Znakova: "cx",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "6 x 525 g",
        tezinaPoJediniciMjere: "525 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/21047.webp",
        },
      },
      title: "Lignja Patagonica 525 g Perla",
      proizvodId: 1425,
    },
  },
  {
    node: {
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "108",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: null,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova:
          "Kolutići i krakovi lignje Patagonica 425 g Perla",
        imeProizvodaDo60ZnakovaEng:
          "Patagonian Squid rings and tentacles 425 g.",
        jedinicaMjere: "kom",
        kataloskiBroj: "21046",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Loligo gahi",
        marketinskoImePerlaProizvodaEng:
          "Patagonian Squid rings and tentacles 425 g.",
        marketinskoImePerlaProizvodaHr:
          "Kolutići i krakovi lignje Patagonica Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "z",
        opisHrDo300Znakova: "s",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "8 x 425 g",
        tezinaPoJediniciMjere: "425 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/21046.webp",
        },
      },
      title: "Kolutići i krakovi lignje Patagonica 425 g Perla",
      proizvodId: 1424,
    },
  },
];
