import React from "react";

import Layout from "../../components/layout.js";
import { useRouter } from "next/router";

import slugify from "slugify";
import Head from "next/head.js";
import {
  // getAllPerlaProizvodi,
  // getAllPerlaProizvodiPaths,
  getAllRecepti,
  getAllReceptiPaths,
} from "../../lib/api2.js";
import Recept from "../../components/Recepti/Recept/index.js";
import PerlaProizvodi from "../../components/Recepti/Recept/PerlaProizvodi/index.js";
import { perlaProizvodiLocal } from "../../perlaProizvodi.js";

export default function News({ pageData, recepti }) {
  const { locale } = useRouter();
  // const router = useRouter();
  const recept = pageData.node.perlaRecepti;
  console.log({ pageData });
  return (
    <Layout receptiNaslovi={recepti.edges}>
      <Head>
        <title>
          {" "}
          {locale === "hr" ? recept.naslovRecepta : recept.naslovReceptaEng}
        </title>

        <meta
          property="og:title"
          content={
            locale === "hr"
              ? `Perla recepti - ${recept.naslovRecepta}`
              : `Perla recepti - ${recept.naslovReceptaEng}`
          }
          key="title"
        />
        <meta
          name="twitter:title"
          content={
            locale === "hr"
              ? `Perla recepti - ${recept.naslovRecepta}`
              : `Perla recepti - ${recept.naslovReceptaEng}`
          }
        />
        <meta
          name="twitter:description"
          content={
            locale === "hr" ? recept.naslovRecepta : recept.naslovReceptaEng
          }
        />
        <meta
          name="twitter:image"
          content={recept.fotografijaRecepta.sourceUrl}
        />
        <meta name="twitter:card" content="summary_large_image" />
        <meta
          name="description"
          content={
            locale === "hr" ? recept.naslovRecepta : recept.naslovReceptaEng
          }
          key="desc"
        />
        <meta
          property="og:description"
          content={
            locale === "hr" ? recept.naslovRecepta : recept.naslovReceptaEng
          }
        />

        <meta
          property="og:image"
          content={recept.fotografijaRecepta.sourceUrl}
        />
      </Head>
      <Recept
        receptData={pageData}
        recept={recepti}
        perlaProizvodi={perlaProizvodiLocal}
      />
      <PerlaProizvodi perlaProizvodi={perlaProizvodiLocal} />
    </Layout>
  );
}

export async function getStaticPaths({ locales }) {
  const recepti = await getAllReceptiPaths();

  const paths = [];

  recepti.edges.forEach(({ node }) => {
    const recipeId = node.id;

    if (!recipeId) {
      console.warn("Skipping recipe due to missing ID:", node);
      return;
    }

    const date = new Date(node.date).toISOString().split("T")[0];

    if (
      !node.perlaRecepti?.naslovRecepta &&
      !node.perlaRecepti?.naslovReceptaEng
    ) {
      console.warn(
        `Skipping recipe with ID ${recipeId} due to missing titles.`
      );
      return;
    }

    // Generate HR path
    if (node.perlaRecepti.naslovRecepta) {
      paths.push({
        params: {
          slug:
            slugify(node.perlaRecepti.naslovRecepta, {
              locale: "hr",
              strict: true,
              lower: true,
            }) + `-${date}`,
          // <--- Ensure this is here
        },
        locale: "hr",
      });
    }

    // Generate EN path
    if (node.perlaRecepti.naslovReceptaEng) {
      paths.push({
        params: {
          slug:
            slugify(node.perlaRecepti.naslovReceptaEng, {
              locale: "en",
              strict: true,
              lower: true,
            }) + `-${date}`,
        },
        locale: "en",
      });
    }
  });

  // --- ADD THIS CONSOLE.LOG ---
  console.log(
    "Paths array generated by getStaticPaths:",
    JSON.stringify(paths.slice(0, 2), null, 2)
  ); // Log first 2 paths for brevity
  // --- END CONSOLE.LOG ---

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  const recepti = await getAllRecepti();
  const currentSlug = params.slug;

  const found = recepti.edges.find(({ node }) => {
    const date = new Date(node.date).toISOString().split("T")[0];

    const hrSlug =
      slugify(node.perlaRecepti?.naslovRecepta || "", {
        locale: "hr",
        strict: true,
        lower: true,
      }) + `-${date}`;

    const enSlug =
      slugify(node.perlaRecepti?.naslovReceptaEng || "", {
        locale: "en",
        strict: true,
        lower: true,
      }) + `-${date}`;

    return hrSlug === currentSlug || enSlug === currentSlug;
  });

  if (!found) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      pageData: found,
      recepti,
    },
  };
}
